import { getCollection } from 'astro:content';
import { getRepo } from './data';

export const directions = [
  { slug: 'mission-desk', name: 'Mission Desk', number: '09', line: 'The work, on the record.', mood: 'Dense · systematic · Shuttle-era', type: 'Inter / JetBrains Mono', colours: ['#f1edde', '#b33520', '#182b3b'], reference: 'NASA — Graphics Standards Manual, 1976', url: 'https://www.nasa.gov/wp-content/uploads/2015/01/nasa_graphics_manual_nhb_1430-2_jan_1976.pdf', rationale: 'A cream, red and navy working publication: project manifests beside a dated operations log, followed by a readable repository ledger. Real descriptions replace an empty poster hero. An original interpretation, with no NASA affiliation.', interaction: 'Jump between builds, unfold monthly commit totals and inspect the full language inventory.' },
  { slug: 'the-independent', name: 'The Independent', number: '10', line: 'Independently built. Openly shared.', mood: 'Editorial · asymmetric · substantial', type: 'Fraunces / Inter / JetBrains Mono', colours: ['#f7f4ea', '#25291f', '#7a3423'], reference: 'Pentagram — editorial design', url: 'https://www.pentagram.com/editorial-design', rationale: 'A newspaper-like reading rhythm: a lead story, narrow dispatch column and unequal project columns. Full writing excerpts and a dated data desk make the substance the design.', interaction: 'Read the front page, browse project briefs and follow dispatches into the writing archive.' },
  { slug: 'parts-catalogue', name: 'Parts Catalogue', number: '11', line: 'Take what you need. See how it works.', mood: 'Industrial · tactile · expandable', type: 'Inter / JetBrains Mono', colours: ['#e4e1d6', '#293127', '#805019'], reference: 'Are.na — collecting ideas', url: 'https://www.are.na/', rationale: 'Software organised like a workshop parts cabinet: numbered drawers, specification plates and service manuals. Native disclosures expose real project detail without requiring JavaScript.', interaction: 'Open the component drawers, inspect specifications, read the bench record and take a service manual.' },
  { slug: 'launch-sequence', name: 'Launch Sequence', number: '06', line: 'Make the small spectacular.', mood: 'Kinetic · staged · optimistic', type: 'Inter / Fraunces / JetBrains Mono', colours: ['#101010', '#df4a24', '#f4f0e7'], reference: 'Mission control interfaces', url: 'https://www.nasa.gov/', rationale: 'Scroll-led chapters turn the portfolio into a legible sequence without hijacking the reader. Original orbital geometry and restrained status language create momentum.', interaction: 'Scroll through full-viewport stages to reveal real project payloads.' },
  { slug: 'signal-noise', name: 'Signal / Noise', number: '07', line: 'Find the signal.', mood: 'Kinetic · nocturnal · responsive', type: 'Inter / Fraunces / JetBrains Mono', colours: ['#090b22', '#8ff4d4', '#f2573d'], reference: 'Signal processing diagrams', url: 'https://www.are.na/', rationale: 'A high-contrast field makes discovery feel spatial while explicit buttons keep every signal accessible without hover or canvas-only content.', interaction: 'Use numbered beacons or movement as an invitation; buttons reveal real projects and writing.' },
  { slug: 'the-machine', name: 'The Machine', number: '08', line: 'Pull the work apart.', mood: 'Explanatory · tactile · electric', type: 'Inter / Fraunces / JetBrains Mono', colours: ['#171b16', '#d9ff45', '#f5f3ec'], reference: 'Industrial control surfaces', url: 'https://www.are.na/', rationale: 'An oversized selector turns project context into an instrument: problem, decision and result are explicit, illustrative lenses rather than invented case-study claims.', interaction: 'Select a project and inspect its three-part deconstruction.' },
  { slug: 'workbench', name: 'Workbench', number: '09', line: 'Built by hand. Logged in detail.', mood: 'Practical · tactile · annotated', type: 'Inter / Fraunces / JetBrains Mono', colours: ['#f2ead9', '#20231f', '#e75b2a', '#275d8c'], reference: 'Workshop manuals and tool boards', url: 'https://www.openstructures.net/', rationale: 'A maker’s bench becomes a truthful information system: measured drawings introduce the work, a stock ledger shows real activity, and project drawers reveal provenance rather than hiding it.', interaction: 'Filter the project drawers, unfold bench notes and inspect the complete workshop log.' },
  { slug: 'broadcast', name: 'Broadcast', number: '10', line: 'Useful software, after dark.', mood: 'Nocturnal · tuned · editorial', type: 'Inter / Fraunces / JetBrains Mono', colours: ['#0b1020', '#f3efe4', '#8cf0c7', '#ff6b4a'], reference: 'Analogue tuning scales and independent radio', url: 'https://www.are.na/', rationale: 'A late-night radio metaphor turns projects into selectable channels, writing into a programme schedule and real language shares into a readable frequency dial—without pretending the static page is live.', interaction: 'Tune between project channels with pointer or keyboard, then read the schedule and frequency bands.' },
  { slug: 'flight-manual', name: 'Flight Manual', number: '05', line: 'Small tools. New horizons.', mood: 'Shuttle-era · systematic · optimistic', type: 'Inter / JetBrains Mono', colours: ['#efeee6', '#ee4b2b', '#182a3c', '#e7803c', '#eab95b'], reference: 'NASA — Graphics Standards Manual, 1976', url: 'https://www.nasa.gov/wp-content/uploads/2015/01/nasa_graphics_manual_nhb_1430-2_jan_1976.pdf', rationale: 'The optimism and clarity of Shuttle-era visual communication: strong numbering, flush-left sans-serif typography and warm red on light paper. A navy orbital plate and orange-gold bands add an original poster-like interpretation. No NASA logo or affiliation.', interaction: 'Choose a payload to open a project brief, then explore the engineering notes.' },
  { slug: 'atlas', name: 'Atlas', number: '01', line: 'An index of useful things.', mood: 'Editorial · precise · expansive', type: 'Fraunces / Inter', colours: ['#f5f3ec', '#191919', '#b83b27'], reference: 'Pentagram — editorial design', url: 'https://www.pentagram.com/editorial-design', rationale: 'Publication-scale typography, decisive rules and an asymmetric reading rhythm. The project index behaves like a table of contents, not a wall of cards.', interaction: 'Filter the index by discipline; unfold the thinking behind each build.' },
  { slug: 'studio', name: 'Studio', number: '02', line: 'Small tools. Big personality.', mood: 'Graphic · playful · direct', type: 'Inter, tightly set / JetBrains Mono', colours: ['#193de8', '#e0fc76', '#f5f3ec'], reference: 'Osmo — interaction library', url: 'https://www.osmo.supply/', rationale: 'Expressive scale and tactile interaction, translated into an original cobalt-and-citron poster. A project selector changes the entire stage, rather than sending you through a carousel.', interaction: 'Choose a project to change the artwork, description and destination.' },
  { slug: 'observatory', name: 'Observatory', number: '03', line: 'Follow a signal.', mood: 'Technical · nocturnal · exploratory', type: 'JetBrains Mono / Inter', colours: ['#091719', '#b7f1d4', '#f1bc77'], reference: 'NASA Science — Universe', url: 'https://science.nasa.gov/universe/', rationale: 'The spatial curiosity of a star atlas, without pretending project data is telemetry. An original schematic constellation is paired with a readable project inspector.', interaction: 'Select an orbital marker to inspect a real repository and its technology.' },
  { slug: 'fieldnotes', name: 'Fieldnotes', number: '04', line: 'Made, noticed, written down.', mood: 'Tactile · thoughtful · personal', type: 'Fraunces / JetBrains Mono', colours: ['#eee5d3', '#364f3e', '#a63f26'], reference: 'Are.na — collecting ideas', url: 'https://www.are.na/', rationale: 'A collection that rewards meandering: generous serif type, ruled paper, margin notes and a pasted-in technical drawing. The notebook metaphor organises real writing rather than manufacturing nostalgia.', interaction: 'Switch notebook topics and open the reading notes before visiting an essay.' },
];

export async function getAlternativeContent() {
  const notes = (await getCollection('projects')).sort((a, b) => (a.data.order ?? 99) - (b.data.order ?? 99));
  const projects = notes.map(note => {
    const repo = getRepo(note.data.repo);
    if (!repo) throw new Error(`Missing alternative project: ${note.data.repo}`);
    return { name: repo.name, title: ({ 'watt-is-it': 'Watt is it?', 'PodcastSync-Local-Mac-App': 'PodcastSync', 'flipoff-Aeroplanes': 'FlipOff', 'zotero-ai-plugin': 'Zotero AI', 'Mac-TreeSpace': 'TreeSpace' } as Record<string, string>)[repo.name] ?? repo.name, description: note.data.tagline, stack: note.data.stack, category: repo.name === 'flipoff-Aeroplanes' || repo.name === 'zotero-ai-plugin' ? 'Web & research' : 'Mac utilities', href: `/projects/${repo.name}`, fork: repo.isFork };
  });
  const articles = (await getCollection('articles')).sort((a, b) => b.data.date.valueOf() - a.data.date.valueOf());
  return { projects, articles };
}
